Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - src/cb/completion.cr
  Enabled: true
  Severity: Convention

Layout/TrailingWhitespace:
  Description: Disallows trailing whitespace.
  Excluded:
  # exclude spec files as some expected output might contain trailing
  # whitespaces.
  - spec/*/***
  Enabled: true