name: CI

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '*.yml'
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '*.yml'

jobs:
  macos-tests:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install crystal
      run: brew install crystal

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: crystal spec --error-on-warnings

  ubuntu-tests:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install LibSSH2
      run: apk add --no-cache libssh2 libssh2-dev libssh2-static

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: crystal spec --error-on-warnings

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Crystal repos
      run: curl -sSL https://crystal-lang.org/install.sh | sudo bash

    - name: Install crystal
      run: sudo apt-get install -y crystal libevent-dev libpcre3-dev libreadline-dev

    - name: Format
      run: crystal tool format --check

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: bin/ameba
