name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: crunchy-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v3
      - name: nix flake check
        run:  nix flake check --print-build-logs --keep-going
