name: TestAarch64CrossBuild

on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: set up cachix
      uses: cachix/cachix-action@v12
      with:
        name: crunchy-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: actions/checkout@v3

    - name: install aarch64-qemu
      run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y
        sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static

    - name: build
      run:  nix build .#packages.aarch64-linux.static
    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      with:
        name: cb-aarch64-linux-static
        path: result/bin/cb
